/*
 * Default Constructor
 * - Compiler is responsible to generate default constructor (NOT JVM).
 *
 * - If we are not writing any constructor in a class, then
 *   the compiler will generate a default constructor.
 *
 * - But if we provide at least ONE constructor explicitly,
 *   then the compiler will NOT generate a default constructor.
 *
 * - Hence, every class in Java will always have a constructor:
 *     → Either the default constructor (provided by the compiler)
 *     → Or a constructor explicitly defined by the programmer
 *   (but never both at the same time).
 *
 * - The default constructor generated by the compiler:
 *     1. Has the same access modifier as the class
 *     2. Has no arguments
 *     3. Its body only contains a call to super()
 *
 * Example 1: Class without constructor → compiler generates default constructor
 * Example 2: Class with explicit constructor → compiler does NOT add default constructor
 */

public class Main {
    public static void main(String[] args) {
        A a = new A(); // Allowed → compiler provides default constructor

        // B b = new B(); // CE: constructor B() is undefined
        B b = new B("Hello"); // Allowed → calls explicit constructor
    }
}
