/*
 * Multithreading
 * Every thread in Java has a priority. It may be the default priority generated by the JVM
 * or a custom priority provided by the programmer.
 *
 * Valid range: 1 to 10
 * - Thread.MIN_PRIORITY (1)
 * - Thread.NORM_PRIORITY (5)
 * - Thread.MAX_PRIORITY (10)
 *
 * Thread Scheduler may use priorities while allocating CPU time.
 * - Higher priority threads are more likely to get CPU first.
 * - Threads with the same priority: execution order is not guaranteed.
 *
 * Methods to get and set priority:
 * - public final int getPriority()
 * - public final void setPriority(int newPriority)
 *
 * IllegalArgumentException is thrown if the priority is set outside 1–10.
 *
 * Notes:
 * - Default priority is Thread.NORM_PRIORITY (5) if not set.
 * - Changing priority is a request to the scheduler; execution order is still JVM-dependent.
 */

public class Main {
    public static void main(String[] args) {
        MyThread myThread = new MyThread();

        // Default priority
        System.out.println("Priority of myThread: " + myThread.getPriority());

        // Set custom priority
        myThread.setPriority(8);
        System.out.println("Priority of myThread: " + myThread.getPriority());
    }
}