/*
 * Multithreading
 * Every thread in Java has a name. It may be a default name generated by the JVM
 * or a custom name provided by the programmer.
 *
 * Methods to get and set thread names:
 * - public final String getName();
 * - public final void setName(String name);
 *
 * Notes:
 * - Every thread is assigned a default name by the JVM if not explicitly set.
 * - Custom names help in debugging and identifying threads easily.
 */

public class Main {
    public static void main(String[] args) {
        // Current main thread
        System.out.println("Main Thread Name: " + Thread.currentThread().getName());

        // Create MyThread
        MyThread myThread = new MyThread();
        System.out.println("MyThread Thread Name: " + myThread.getName());

        // Rename MyThread
        myThread.setName("Rishabh Thread");
        System.out.println("MyThread Thread Name: " + myThread.getName());
    }
}