/*
 * Inner Classes
 * Anonymous Inner Class
 *
 * Sometimes we can declare a class without a name; such types of inner classes
 * are called anonymous inner classes.
 * The main purpose of an anonymous inner class is for instant use (one-time usage).
 *
 * Anonymous inner classes can:
 * - Extend a class
 * - Implement an interface
 * - Be defined inside method arguments
 *
 * Example below demonstrates an anonymous inner class that extends Popcorn.
 * - popcorn1 → normal Popcorn object, calls original taste() → prints "Salty"
 * - popcorn2 → anonymous subclass of Popcorn, overrides taste() → prints "Spicy"
 * - getClass().getName() shows the class name:
 *     - popcorn1 → Popcorn
 *     - popcorn2 → synthetic name generated by JVM (like Main$1)
 */

public class Main {
    public static void main(String[] args) {
        Popcorn popcorn1 = new Popcorn();
        popcorn1.taste(); // Salty

        Popcorn popcorn2 = new Popcorn() {
            public void taste() {
                System.out.println("Spicy");
            }
        };
        popcorn2.taste(); // Spicy

        System.out.println(popcorn1.getClass().getName()); // Popcorn
        System.out.println(popcorn2.getClass().getName()); // Main$1
    }
}

